version: "3.8"

services:
  app:
    image: dental-clinic-lp:latest
    container_name: dental-clinic-lp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always